[package]
name = "api_resp_buff"
version = "0.1.0"
authors = ["PrisionMike <su.sh2396@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
